
services:
    # ================================
    # Twig extensions
    # ================================

    naoned.vanao.twig.record_extension:
        class: Naoned\EdnaoClientBundle\Twig\IframeExtension
        calls:
            - [ setContainer, [@service_container]]
        tags:
            - { name: twig.extension }
